<?php
// This script and data application were generated by AppGini 5.40
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/external_contact.php");
	include("$currDir/external_contact_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('external_contact');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "external_contact";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`external_contact`.`id`" => "id",
		"`external_contact`.`last_name`" => "last_name",
		"`external_contact`.`first_name`" => "first_name",
		"`external_contact`.`poste`" => "poste",
		"`external_contact`.`company_name`" => "company_name",
		"`external_contact`.`email`" => "email",
		"CONCAT_WS('-', LEFT(`external_contact`.`phone`,3), MID(`external_contact`.`phone`,4,3), RIGHT(`external_contact`.`phone`,4))" => "phone",
		"CONCAT_WS('-', LEFT(`external_contact`.`alternate_phone`,3), MID(`external_contact`.`alternate_phone`,4,3), RIGHT(`external_contact`.`alternate_phone`,4))" => "alternate_phone",
		"`external_contact`.`country`" => "country",
		"`external_contact`.`info`" => "info"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`external_contact`.`id`',
		2 => '`external_contact`.`last_name`',
		3 => '`external_contact`.`first_name`',
		4 => 4,
		5 => '`external_contact`.`company_name`',
		6 => 6,
		7 => 7,
		8 => 8,
		9 => '`external_contact`.`country`',
		10 => 10,
		
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`external_contact`.`id`" => "id",
		"`external_contact`.`last_name`" => "last_name",
		"`external_contact`.`first_name`" => "first_name",
		"`external_contact`.`poste`" => "poste",
		"`external_contact`.`company_name`" => "company_name",
		"`external_contact`.`email`" => "email",
		"CONCAT_WS('-', LEFT(`external_contact`.`phone`,3), MID(`external_contact`.`phone`,4,3), RIGHT(`external_contact`.`phone`,4))" => "phone",
		"CONCAT_WS('-', LEFT(`external_contact`.`alternate_phone`,3), MID(`external_contact`.`alternate_phone`,4,3), RIGHT(`external_contact`.`alternate_phone`,4))" => "alternate_phone",
		"`external_contact`.`country`" => "country",
		"`external_contact`.`info`" => "info"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array( 

		"`external_contact`.`id`" => "ID",
		"`external_contact`.`last_name`" => "Last name",
		"`external_contact`.`first_name`" => "First name",
		"`external_contact`.`poste`" => "poste",
		"`external_contact`.`company_name`" => "Company name",
		"`external_contact`.`email`" => "Email",
		"CONCAT_WS('-', LEFT(`external_contact`.`phone`,3), MID(`external_contact`.`phone`,4,3), RIGHT(`external_contact`.`phone`,4))" => "Phone",
		"CONCAT_WS('-', LEFT(`external_contact`.`alternate_phone`,3), MID(`external_contact`.`alternate_phone`,4,3), RIGHT(`external_contact`.`alternate_phone`,4))" => "Alternate phone",
		"`external_contact`.`country`" => "Country",
		"`external_contact`.`info`" => "Info"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`external_contact`.`id`" => "id",
		"`external_contact`.`last_name`" => "last_name",
		"`external_contact`.`first_name`" => "first_name",
		"`external_contact`.`poste`" => "poste",
		"`external_contact`.`company_name`" => "company_name",
		"`external_contact`.`email`" => "email",
		"CONCAT_WS('-', LEFT(`external_contact`.`phone`,3), MID(`external_contact`.`phone`,4,3), RIGHT(`external_contact`.`phone`,4))" => "phone",
		"CONCAT_WS('-', LEFT(`external_contact`.`alternate_phone`,3), MID(`external_contact`.`alternate_phone`,4,3), RIGHT(`external_contact`.`alternate_phone`,4))" => "alternate_phone",
		"`external_contact`.`country`" => "country",
		"`external_contact`.`info`" => "info"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom="`external_contact` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "external_contact_view.php";
	$x->RedirectAfterInsert = "external_contact_view.php?SelectedID=#ID#";
	$x->TableTitle = "External Contact";
	$x->TableIcon = "resources/table_icons/account_balances.png";
	$x->PrimaryKey = "`external_contact`.`id`";
	$x->DefaultSortField = '2';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth   = array(  100, 100, 100, 100, 100, 100, 80, 80, 80, 100, 100);
	$x->ColCaption = array("Last name", "First name", "Function"," Company name", "Email", "Phone", "Alternate_phone", "Country", "Info");
	$x->ColFieldName = array('last_name', 'first_name', 'poste', 'company_name', 'email', 'phone', 'alternate_phone', 'country', 'info');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 10);

	$x->Template = 'templates/external_contact_templateTV.html';
	$x->SelectedTemplate = 'templates/external_contact_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `external_contact`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='external_contact' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `external_contact`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='external_contact' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`external_contact`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: external_contact_init
	$render=TRUE;
	if(function_exists('external_contact_init')){
		$args=array();
		$render=external_contact_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: external_contact_header
	$headerCode='';
	if(function_exists('external_contact_header')){
		$args=array();
		$headerCode=external_contact_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: external_contact_footer
	$footerCode='';
	if(function_exists('external_contact_footer')){
		$args=array();
		$footerCode=external_contact_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>