<?php
// This script and data application were generated by AppGini 5.40
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/internal_contact.php");
	include("$currDir/internal_contact_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('internal_contact');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "internal_contact";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`internal_contact`.`id`" => "id",
		"`internal_contact`.`cec`" => "cec",
		"`internal_contact`.`last_name`" => "last_name",
		"`internal_contact`.`first_name`" => "first_name",
		"`internal_contact`.`poste`" => "poste",
		"`internal_contact`.`email`" => "email",
		"CONCAT_WS('-', LEFT(`internal_contact`.`phone`,3), MID(`internal_contact`.`phone`,4,3), RIGHT(`internal_contact`.`phone`,4))" => "phone",
		"`internal_contact`.`country`" => "country",
		"`internal_contact`.`info`" => "info"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`internal_contact`.`id`',
		2 => '`internal_contact`.`cec`',
		3 => 3,
		4 => 4,
		5 => '`internal_contact`.`company_name`',
		6 => 6,
		7 => 7,
		8 => '`internal_contact`.`country`',
		9 => 9,
		
		
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`internal_contact`.`id`" => "id",
		"`internal_contact`.`cec`" => "cec",
		"`internal_contact`.`last_name`" => "last_name",
		"`internal_contact`.`first_name`" => "first_name",
		"`internal_contact`.`poste`" => "poste",
		"`internal_contact`.`email`" => "email",
		"CONCAT_WS('-', LEFT(`internal_contact`.`phone`,3), MID(`internal_contact`.`phone`,4,3), RIGHT(`internal_contact`.`phone`,4))" => "phone",
		"`internal_contact`.`country`" => "country",
		"`internal_contact`.`info`" => "info"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array( 
		"`internal_contact`.`id`" => "ID",
		"`internal_contact`.`cec`" => "CEC",
		"`internal_contact`.`last_name`" => "Last name",
		"`internal_contact`.`first_name`" => "First name",
		"`internal_contact`.`poste`" => "poste",
		"`internal_contact`.`email`" => "Email",
		"CONCAT_WS('-', LEFT(`internal_contact`.`phone`,3), MID(`internal_contact`.`phone`,4,3), RIGHT(`internal_contact`.`phone`,4))" => "Phone",
		"`internal_contact`.`country`" => "Country",
		"`internal_contact`.`info`" => "Info"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`internal_contact`.`id`" => "id",
		"`internal_contact`.`cec`" => "cec",
		"`internal_contact`.`last_name`" => "last_name",
		"`internal_contact`.`first_name`" => "first_name",
		"`internal_contact`.`poste`" => "poste",
		"`internal_contact`.`email`" => "email",
		"CONCAT_WS('-', LEFT(`internal_contact`.`phone`,3), MID(`internal_contact`.`phone`,4,3), RIGHT(`internal_contact`.`phone`,4))" => "phone",
		"`internal_contact`.`country`" => "country",
		"`internal_contact`.`info`" => "info"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom="`internal_contact` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "internal_contact_view.php";
	$x->RedirectAfterInsert = "internal_contact_view.php?SelectedID=#ID#";
	$x->TableTitle = "Internal Contact";
	$x->TableIcon = "resources/table_icons/account_balances.png";
	$x->PrimaryKey = "`internal_contact`.`id`";
	$x->DefaultSortField = '2';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth   = array(  100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100);
	$x->ColCaption = array("CEC","Last name", "First name", "Function", "Email", "Phone", "Country", "Info");
	$x->ColFieldName = array('cec','last_name', 'first_name', 'poste', 'email', 'phone', 'country', 'info');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 10);

	$x->Template = 'templates/internal_contact_templateTV.html';
	$x->SelectedTemplate = 'templates/internal_contact_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `internal_contact`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='internal_contact' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `internal_contact`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='internal_contact' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`internal_contact`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: internal_contact_init
	$render=TRUE;
	if(function_exists('internal_contact_init')){
		$args=array();
		$render=internal_contact_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: internal_contact_header
	$headerCode='';
	if(function_exists('internal_contact_header')){
		$args=array();
		$headerCode=internal_contact_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: internal_contact_footer
	$footerCode='';
	if(function_exists('internal_contact_footer')){
		$args=array();
		$footerCode=internal_contact_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>